
#import = ["~/.config/alacritty/dracula.toml"]
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

#import = ["~/.config/alacritty/nord.toml"]

[shell]
#program = "/bin/bash"
program = "/bin/zsh"



[window]

dimensions = { columns = 80, lines = 24 }

#position = { x = 865, y = 420 }

#dynamic_padding = true

padding = { x = 15, y = 15 }

opacity = 0.90

[font]

normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }



#normal = { family = "FiraCode Nerd Font", style = "Regular" }
#bold = { family = "FiraCode Nerd Font", style = "Bold" }
#italic = { family = "FiraCode Nerd Font", style = "Italic" }
#bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

size = 15


[cursor]


#style = { "Beam", "Off" }

#style = { <shape>, <blinking> }
style = "Beam"

vi_mode_style = "Block"

thickness = 0.2
unfocused_hollow = false


[selection]

save_to_clipboard = true


[terminal]


osc52 = "CopyPaste"



[mouse]


hide_when_typing = true


[keyboard]

bindings = [
{ key = "C", mods = "Control|Alt", action = "Copy"},
{ key = "V", mods = "Control|Alt", action = "Paste"},
{ key = "T", mods = "Control", action = "SpawnNewInstance"},
]


[debug]

render_timer = false
renderer = "None"



